name: Test Building

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.x'  # Specify the version of Ruby you need

      - name: Install Bundler
        run: gem install bundler

      - name: Install Jekyll Dependencies
        run: bundle install

      - name: Build Jekyll
        run: bundle exec jekyll build
        working-directory: ./  # Assuming your Jekyll project is in the root directory